
"""
Add your CosmosDB NoSQL database schema in this file

For example:

type Book @model {
  id: ID
  title: String
}

"""
type NrSeries {
  customer: Int
  order: Int
  invoice: Int
  cost: Int
}

type company @model {
  id: ID
  name: String
  address: String
  zip: String
  city: String
  phone: String
  email: String
  bankAccount: String
  nrSeries: NrSeries
}

type customers @model {
  id: ID
  name: String
  address: String
  zip: String
  city: String
  phone: String
  email: String
  created: String
  created_by: String
  updated: String
  updated_by: String
  deleted: Boolean
}

type products @model {
  id: ID
  name: String
  description: String
  unit: String
  price: Float
  storage: Float
  account: Int
  active: Boolean
  webshop: Boolean
  image: String
  created: String
  created_by: String
  updated: String
  updated_by: String
}

type orderLines {
  id: ID
  date: String
  product: String
  price: Float
  amount: Float
  unit: String
  comment: String
  user: String
}

type orders @model {
  id: ID
  name: String
  customer: Int
  date: String
  active: Boolean
  sum: Float
  invoices: [Int]
  orderLines: [orderLines]
  created: String
  created_by: String
  updated: String
  updated_by: String
  deleted: Boolean
}